export const SCENARIOS = {
  'at-most-once': {
    id: 'at-most-once',
    name: 'At-most-once',
    icon: '💨',
    blurb: 'Fire and forget. May lose.',
    mode: 'at-most-once',
    showIdempotency: false,
    showDLQ: false,
    defaultTool: 'storagequeue',
    category: 'guarantees',
  },
  'at-least-once': {
    id: 'at-least-once',
    name: 'At-least-once',
    icon: '🔁',
    blurb: 'Retry until ACK. May duplicate.',
    mode: 'at-least-once',
    showIdempotency: true,
    showDLQ: false,
    defaultTool: 'servicebus',
    category: 'guarantees',
  },
  'exactly-once': {
    id: 'exactly-once',
    name: 'Exactly-once',
    icon: '🛡️',
    blurb: 'Broker dedup + transactions.',
    mode: 'exactly-once',
    showIdempotency: true,
    showDLQ: false,
    defaultTool: 'servicebus',
    category: 'guarantees',
  },
  dlq: {
    id: 'dlq',
    name: 'Dead Letter Queue',
    icon: '🪦',
    blurb: 'Poison messages → DLQ after N retries.',
    mode: 'at-least-once',
    showIdempotency: false,
    showDLQ: true,
    showOutbox: false,
    defaultTool: 'servicebus',
    category: 'patterns',
  },
  outbox: {
    id: 'outbox',
    name: 'Outbox Pattern',
    icon: '📦',
    blurb: 'Atomic DB write + relay to broker.',
    mode: 'at-least-once',
    showIdempotency: false,
    showDLQ: false,
    showOutbox: true,
    defaultTool: 'servicebus',
    category: 'patterns',
  },
  inbox: {
    id: 'inbox',
    name: 'Inbox Pattern',
    icon: '📥',
    blurb: 'Consumer-side dedup via atomic inbox table.',
    mode: 'at-least-once',
    showIdempotency: false,
    showDLQ: false,
    showOutbox: false,
    showInbox: true,
    defaultTool: 'servicebus',
    category: 'patterns',
  },
}

export const CATEGORIES = [
  {
    id: 'guarantees',
    title: 'Delivery Guarantees',
    dotClass: 'cat-dot-guarantees',
    scenarios: ['at-most-once', 'at-least-once', 'exactly-once'],
  },
  {
    id: 'patterns',
    title: 'Reliability Patterns',
    dotClass: 'cat-dot-patterns',
    scenarios: ['dlq', 'outbox', 'inbox'],
  },
]

export const SPEEDS = [
  { label: 'Slow', value: 2200 },
  { label: 'Normal', value: 1400 },
  { label: 'Fast', value: 700 },
]
