export const TOOLS = {
  servicebus: {
    name: 'Azure Service Bus',
    brokerLabel: 'SERVICE BUS',
    brokerDesc: 'Queue / Topic',
    desc: "<strong>Default:</strong> at-least-once with <code>PeekLock</code> + <code>Complete()</code>. <strong>Exactly-once</strong> via <code>RequiresDuplicateDetection=true</code> (window up to 7 days). <strong>Native DLQ</strong> after MaxDeliveryCount is exceeded.",
    supports: ['at-most-once', 'at-least-once', 'exactly-once'],
    supportsDLQ: true,
    group: 'Azure',
  },
  'servicebus-sessions': {
    name: 'Azure Service Bus + Sessions',
    brokerLabel: 'SB SESSIONS',
    brokerDesc: 'FIFO per SessionId',
    desc: "<strong>Sessions</strong> guarantee FIFO order per <code>SessionId</code>. Combine with duplicate detection for ordered exactly-once. <strong>Native DLQ</strong> after MaxDeliveryCount.",
    supports: ['at-least-once', 'exactly-once'],
    supportsDLQ: true,
    group: 'Azure',
  },
  eventhubs: {
    name: 'Azure Event Hubs',
    brokerLabel: 'EVENT HUBS',
    brokerDesc: 'Partitions + Offsets',
    desc: "<strong>Default:</strong> at-least-once (Kafka-like). Partitioned by <code>PartitionKey</code>. Checkpoint-based. No native dedup. <strong>No native DLQ</strong>: must be implemented manually (separate topic / event handler).",
    supports: ['at-most-once', 'at-least-once'],
    supportsDLQ: false,
    group: 'Azure',
  },
  eventgrid: {
    name: 'Azure Event Grid',
    brokerLabel: 'EVENT GRID',
    brokerDesc: 'Pub/Sub HTTP',
    desc: "<strong>Default:</strong> at-least-once with exponential retry (24h) + <strong>Dead-Letter to Blob Storage</strong>. CloudEvents 1.0 schema. No native dedup.",
    supports: ['at-least-once'],
    supportsDLQ: true,
    group: 'Azure',
  },
  storagequeue: {
    name: 'Azure Storage Queue',
    brokerLabel: 'STORAGE QUEUE',
    brokerDesc: 'Simple queue',
    desc: "<strong>Default:</strong> at-least-once. Simpler and cheaper than Service Bus. <code>VisibilityTimeout</code> hides the message while consumer processes. <strong>No native DLQ</strong>: implement via DequeueCount check.",
    supports: ['at-most-once', 'at-least-once'],
    supportsDLQ: false,
    group: 'Azure',
  },
  rabbitmq: {
    name: 'RabbitMQ',
    brokerLabel: 'RABBITMQ',
    brokerDesc: 'Exchange + Queue',
    desc: "<strong>Default:</strong> at-least-once with <code>publisher confirms</code> + <code>manual ack</code>. <strong>Native DLX</strong> (Dead Letter Exchange) on nack/reject or TTL expiry. Quorum queues for HA.",
    supports: ['at-most-once', 'at-least-once'],
    supportsDLQ: true,
    group: 'Others',
  },
  kafka: {
    name: 'Apache Kafka',
    brokerLabel: 'KAFKA',
    brokerDesc: 'Topics + Partitions',
    desc: "<strong>Default:</strong> at-least-once. <strong>Exactly-once</strong> via idempotent producer + transactions (EOS). <strong>No native DLQ</strong>: common pattern is a dedicated dead-letter topic.",
    supports: ['at-most-once', 'at-least-once', 'exactly-once'],
    supportsDLQ: false,
    group: 'Others',
  },
}

export const TOOL_GROUPS = ['Azure', 'Others']
